*** Variables ***
${TRANSFER_AMOUNT}           100
${EXPECTED_AMOUNT_TEXT}      KES 100.00
# Tariff charged on a Send to Other transfer. Set to the current tariff for the
# environment; the transfer debit is the principal plus this charge.
${SEND_TO_OTHER_CHARGE}      KES 0.00
${OTHER_MOBILE_NUMBER}       0714975875
${CONTACT_NAME}              Tsho
${CONTACT_LOCAL_NUMBER}      700480198
${VOOMA_TRANSFER_AMOUNT}     100
${VOOMA_EXPECTED_AMOUNT}     KES 100.00
${VOOMA_CONTACT_NAME}        Tsho
${VOOMA_CONTACT_NUMBER}      700480198
${BANK_TRANSFER_AMOUNT}      1000
${BANK_EXPECTED_AMOUNT}      KES 1,000.00
${BANK_AMOUNT_ON_FORM}       1,000.00
${BANK_PAYMENT_REASON}       automated testing
${KCB_ACCOUNT_NUMBER}        1126055190
${KCB_ACCOUNT_NAME}          ELISHAMA GREENS LIMITED
${PESALINK_BANK_NAME}        I and M Bank
${PESALINK_ACCOUNT_NUMBER}   00803739186150
${PESALINK_MOBILE_NUMBER}    0714975875
${PESALINK_MOBILE_NAME}      Pesalink UserTest
${PESALINK_PAYMENT_REASON}   automated test
${AIRTIME_AMOUNT}            50
${AIRTIME_EXPECTED_AMOUNT}   KES 50.00
${AIRTIME_AMOUNT_ON_FORM}    50.00
${AIRTIME_OTHER_NUMBER}      714975875
${AIRTIME_PROVIDER}          Safaricom
${VOOMA_PAY_AMOUNT}          50
${VOOMA_PAY_EXPECTED_AMOUNT}    KES 50.00
${VOOMA_PAY_AMOUNT_ON_FORM}     50.00
${VOOMA_TILL_NUMBER}         166166
${VOOMA_MERCHANT_NAME_TEXT}    QUICKMART
${VOOMA_PAYBILL_NUMBER}      100235
${VOOMA_PAYBILL_ACCOUNT}     10025
${VOOMA_BILLER_NAME_TEXT}    Libre5
${VOOMA_BUY_GOODS_TYPE}      VOOMA Buy Goods
${VOOMA_PAY_BILL_TYPE}       VOOMA Pay Bill
${LIPA_TILL_NUMBER}          7691985
${LIPA_MERCHANT_NAME_TEXT}    KIKUYUCATHOLICPARISH
${LIPA_AMOUNT}               50
${LIPA_EXPECTED_AMOUNT}      KES 50.00
${LIPA_AMOUNT_ON_FORM}       50.00
${LIPA_SERVICE_TYPE}         Lipa Na KCB

# Lipa Karo (school fees) from Transact
${LIPA_KARO_SCHOOL_NAME}         ALLIANCE GIRLS HIGH SCHOOL
${LIPA_KARO_SCHOOL_ACCOUNT}      1151244899
${LIPA_KARO_STUDENT_NAME}        Test Student
${LIPA_KARO_AMOUNT}              30000
${LIPA_KARO_AMOUNT_ON_FORM}      30,000.00
${LIPA_KARO_EXPECTED_AMOUNT}     KES 30,000.00

# Placeholder till: no valid M-Pesa merchant code is available yet.
${MPESA_TILL_NUMBER}         166166
${MPESA_PAYBILL_NUMBER}      522533
${MPESA_PAYBILL_ACCOUNT}     7691985
${MPESA_BILLER_NAME_TEXT}    M-Pesa One Till Suspense account
${MPESA_AMOUNT}              50
${MPESA_EXPECTED_AMOUNT}     KES 50.00
${MPESA_AMOUNT_ON_FORM}      50.00
${MPESA_PAYMENT_REASON}      Automated test
${UTILITY_BILLER_NAME}       NAIROBI CITY WATER
${UTILITY_ACCOUNT_NUMBER}    5000075
${UTILITY_ACCOUNT_NAME}      Esther Ndungu Amollo
${UTILITY_PAYBILL_NUMBER}    40029
${UTILITY_TRANSACTION_TYPE}    Pay Bill

# Nairobi Water and Sewerage Company (paybill 40029)
${NAIROBI_WATER_BILLER_NAME}      NAIROBI CITY WATER
${NAIROBI_WATER_PAYBILL_NUMBER}   40029
${NAIROBI_WATER_ACCOUNT_NUMBER}   5000075
${NAIROBI_WATER_ACCOUNT_NAME}     Esther Ndungu Amollo
${NAIROBI_WATER_TRANSACTION_TYPE}    Pay Bill

# KPLC Billers (Kenya Power and Lighting Company)
# Display names match the biller directory exactly (uppercase).
${KPLC_PREPAID_BILLER_NAME}      KPLC PREPAID
${KPLC_PREPAID_PAYBILL_NUMBER}   40003
${KPLC_PREPAID_ACCOUNT_NUMBER}   10000000000
${KPLC_POSTPAID_BILLER_NAME}     KPLC POSTPAID
${KPLC_POSTPAID_PAYBILL_NUMBER}  40096
${KPLC_POSTPAID_ACCOUNT_NUMBER}  4012345678
${KPLC_TRANSACTION_TYPE}         Pay Bill
${KPLC_PAYBILL_NUMBER}           888880
# Vooma wallet row on the Select Account > Wallet tab (masked MSISDN).
${VOOMA_WALLET_MASKED}           254116****61

${DEPOSIT_AMOUNT}            50
${DEPOSIT_EXPECTED_AMOUNT}    KES 50.00
${DEPOSIT_AMOUNT_ON_FORM}    50.00
${DEPOSIT_SOURCE_TYPE}       M-Pesa
${DEPOSIT_SOURCE_MOBILE}     +254116503161
${DEPOSIT_SERVICE_TYPE}      Deposit
${ACCOUNT_MASKED}            117****940
${ACCOUNT_NUMBER}            1179924940
${WITHDRAW_AMOUNT}           50
${WITHDRAW_AMOUNT_ON_FORM}    50.00
${WITHDRAW_EXPECTED_AMOUNT}    KES 50.00
${WITHDRAW_SERVICE_TYPE}     Withdraw
${WITHDRAW_AGENT_OPTION}     KCB Agent
# Placeholder agent: no valid KCB agent number is available yet.
${WITHDRAW_AGENT_NUMBER}     123456

${SPLIT_BILL_NAME}           Team lunch
${SPLIT_BILL_AMOUNT}         100
${SPLIT_BILL_AMOUNT_ON_FORM}    100.00
${SPLIT_BILL_EXPECTED_AMOUNT}    KES 100.00
${SPLIT_BILL_PARTICIPANT_NUMBER}    714975875
# The account holder is counted alongside the participants they add.
${SPLIT_BILL_PARTICIPANT_SUMMARY_TEXT}    Splitting with (2)

${QR_AMOUNT}                 50
${QR_AMOUNT_ON_FORM}         50.00
${QR_EXPECTED_AMOUNT}        KES 50.00

${MOBILE_LOAN_TYPE}          KCB Mobile Loan
${MOBILE_LOAN_AMOUNT}        10000
${MOBILE_LOAN_AMOUNT_ON_FORM}    10,000.00
${MOBILE_LOAN_DURATION}      30 Days Loan
${MOBILE_LOAN_DURATION_ON_FORM}    30 Days

${PERSONAL_LOAN_TYPE}        Salary Advance
${PERSONAL_LOAN_AMOUNT}      50000
${PERSONAL_LOAN_AMOUNT_ON_FORM}    50,000.00
${PERSONAL_LOAN_DURATION}    3 Months Loan
${PERSONAL_LOAN_DURATION_ON_FORM}    3 Months
${CHECKOFF_LOAN_TYPE}        Check Off Loan
${CHECKOFF_LOAN_AMOUNT}      500000
${CHECKOFF_LOAN_AMOUNT_ON_FORM}    500,000.00
${CHECKOFF_LOAN_MONTHS}      5
${CHECKOFF_LOAN_DURATION_ON_FORM}    5 Months

${TARIFF_TRANSACTION_TYPE}    Send to M-Pesa
${TARIFF_AMOUNT}             1000
${TARIFF_AMOUNT_ON_FORM}     1,000.00
${TARIFF_HIGHER_AMOUNT}      50000
${TARIFF_HIGHER_AMOUNT_ON_FORM}    50,000.00

# MMF Calculator
${MMF_CAPITAL}                        100000
${MMF_CAPITAL_ON_FORM}                100,000.00
${MMF_CONTRIBUTION}                   5000
${MMF_CONTRIBUTION_ON_FORM}           5,000.00
${MMF_DURATION_MONTHS}                30
${MMF_DURATION_ON_FORM}               30 Months

# Scheduled Payments
${SCHEDULE_AMOUNT}                    50
${SCHEDULE_AMOUNT_ON_FORM}            50.00
${SCHEDULE_EXPECTED_AMOUNT}           KES 50.00

# PayPal
${PAYPAL_EMAIL}                       jossymkn931@gmail.com

# Manage Statements / Get Statements
${STATEMENT_EMAIL}                    jossymkn931@gmail.com
${STATEMENT_FORMAT}                   PDF
${STATEMENT_DELIVERY}                 Via Email
${SCHEDULE_VOOMA_SELF_NAME}           Robot vooma to self
${SCHEDULE_VOOMA_OTHER_NAME}          Robot vooma to other
${SCHEDULE_MPESA_SELF_NAME}           Robot mpesa to self
${SCHEDULE_MPESA_OTHER_NAME}          Robot mpesa to other
${SCHEDULE_BANK_NAME}                 Robot kcb transfer
${SCHEDULE_PESALINK_NAME}             Robot pesalink transfer
${SCHEDULE_VOOMA_MERCHANT_NAME}       Robot vooma merchant
${SCHEDULE_UTILITY_NAME}              Robot utility bill
${SCHEDULE_NARRATION}                 automated test
${SCHEDULE_FREQUENCY}                 Never
${SCHEDULE_RECIPIENT_NAME_TEXT}       ANDREW DERRICK MAKOKHA
# Insurance
${PERSONAL_ACCIDENT_INDEX}            0
${LAST_EXPENSE_INDEX}                 1
${MOTOR_PRIVATE_INDEX}                2
${INSURANCE_TERMS_PAGE_FLINGS}        12
${MOTOR_REGISTRATION}                 KDG 840D
${MOTOR_ESTIMATED_VALUE}              1000000
${MOTOR_WINDSCREEN_COVER}             20000
${MOTOR_ENTERTAINMENT_UNIT}           10000
${MOTOR_PRIVATE_PRODUCT_NAME}         Motor Private Insurance
${INDIVIDUAL_ACCIDENT_INDEX}          1
${PERSONAL_ACCIDENT_PRODUCT_NAME}     Student & Individual Personal Accident Insurance
${STUDENT_ACCIDENT_6M_INDEX}          0
${STUDENT_ACCIDENT_12M_INDEX}         2
${NUCLEAR_LAST_EXPENSE_INDEX}         0
${LAST_EXPENSE_PRODUCT_NAME}          Last Expense Insurance
${EXTENDED_LAST_EXPENSE_INDEX}        1